# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x08notifier\".\n\rupdateRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"!\n\x0eupdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32M\n\x08Notifier\x12\x41\n\x0cnotifyUpdate\x12\x17.notifier.updateRequest\x1a\x18.notifier.updateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEREQUEST']._serialized_start=32
  _globals['_UPDATEREQUEST']._serialized_end=78
  _globals['_UPDATERESPONSE']._serialized_start=80
  _globals['_UPDATERESPONSE']._serialized_end=113
  _globals['_NOTIFIER']._serialized_start=115
  _globals['_NOTIFIER']._serialized_end=192
# @@protoc_insertion_point(module_scope)
